### ISSUE TITLE
Replace webpack-isomorphic-tools with isomorphic-webpack

### ISSUE THREAD

**Issue by gajus** [xkawi/react-universal-saga#10]
Hello @xkawi 👋 ,

I am the author of [isomorphic-webpack](https://github.com/gajus/isomorphic-webpack). `isomorphic-webpack` is an abstraction used to re-use JavaScript code between server and client. Its been quietly maturing in garage for a few months now and we are using it in production on 2 sites.

However, the [Rule of Three](https://blog.codinghorror.com/rule-of-three/) states that this project is not mature to be "advertised" as ready for production before at least 3 different projects implement it.

I'd like to work with you to re-implement `react-universal-saga` using `isomorphic-webpack`. Hopefully, it will reduce the amount of boilerplate code and make the example itself easier to understand. Along the way I'd like to hear your ideas for improvement and suggestions for documentation.

Have you got time to catch up on Skype/ Slack/ IRC/ ... ?

**Comment by xkawi** [comment]
@gajus thanks for initiating this issue. Honestly, I am not expert with webpack nor webpack-isomorphic-tool. So, feel free to fork `react-universal-saga`, make the changes to use `isomorphic-webpack` and create PR for it? think we can use this issue for any discussion as well.

**Comment by gajus** [comment]
Sounds like a plan. :-) Please assign the issue to me.

**Comment by xkawi** [comment]
going to close this as no updates so far. feel free to open again if there are updates. thanks.
