### ISSUE TITLE
Noticed some depreciation warnings on a clean pm install

### ISSUE THREAD

**Issue by roderik** [xkawi/react-universal-saga#2]
```
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated bootstrap-sass-loader@1.0.10: Replaced by bootstrap-loader. Please upgrade.
npm WARN deprecated css-list@0.1.3: Deprecated.
```

**Comment by xkawi** [comment]
Hi roderik, thanks for reporting. I am aware of that warning. Think it is related to webpack, which I am not that familiar yet. Though it is in my todo list to clean up as soon as I can. Welcome any PR as well.

**Comment by xkawi** [comment]
Made the changes on a4526e3 and going to close this issue.
NOTE: css-list warning could not be solved because it is a dependency of font-awesome-webpack, which has not been updated by the author.
